import type { Metadata } from "next";
import "./globals.css";
import {Navbar} from "@/components/Layout/Navbar";
import {Footer} from "@/components/Layout/Footer";

export const metadata: Metadata = {
  title: "Dev.portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
